// Ghar Bazaar - Seed Data for Rental Marketplace
// Demo brokers, renters, and properties with Cloudinary / high-res imagery

const demoBrokers = [
  {
    id: "B001",
    name: "Rajesh Sharma",
    email: "rajesh.broker@gharbazaar.com",
    phone: "+91 98201 12345",
    role: "broker",
    agencyName: "Apex Realty Mumbai",
    emailVerified: true
  },
  {
    id: "B002",
    name: "Sunita Patil",
    email: "sunita.broker@gharbazaar.com",
    phone: "+91 98334 56789",
    role: "broker",
    agencyName: "Metro Stays & Housing",
    emailVerified: true
  },
  {
    id: "B003",
    name: "Vikram Mehta",
    email: "vikram.broker@gharbazaar.com",
    phone: "+91 98192 34567",
    role: "broker",
    agencyName: "Urban Nest Properties",
    emailVerified: true
  }
];

const demoUsers = [
  {
    id: "U101",
    name: "Rahul Verma",
    email: "rahul.renter@gmail.com",
    phone: "+91 98765 43210",
    role: "user",
    emailVerified: true
  }
];

const demoProperties = [
  {
    id: "P001",
    brokerId: "B001",
    brokerName: "Rajesh Sharma",
    brokerPhone: "+91 98201 12345",
    brokerEmail: "rajesh.broker@gharbazaar.com",
    agencyName: "Apex Realty Mumbai",
    title: "Furnished Private Room in Malad West",
    location: "Malad West, Mumbai",
    area: "malad",
    type: "private",
    price: 12500,
    deposit: 25000,
    badge: "Verified",
    rating: 4.9,
    beds: "1 Bed",
    bath: "Private Bath",
    size: "180 sq.ft",
    amenities: ["WiFi", "AC", "Wardrobe", "Attached Bath", "Power Backup"],
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=85",
    images: [{ url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=85", public_id: "seed_p001_1" }],
    description: "Bright furnished private room in a peaceful residential pocket of Malad West. Quick 5-min walk to Link Road and metro station. Ideal for students and working professionals.",
    availability: "available",
    featured: true
  },
  {
    id: "P002",
    brokerId: "B001",
    brokerName: "Rajesh Sharma",
    brokerPhone: "+91 98201 12345",
    brokerEmail: "rajesh.broker@gharbazaar.com",
    agencyName: "Apex Realty Mumbai",
    title: "Shared PG Near Andheri Station",
    location: "Andheri East, Mumbai",
    area: "andheri",
    type: "pg",
    price: 9800,
    deposit: 15000,
    badge: "Popular",
    rating: 4.8,
    beds: "2 Beds",
    bath: "Shared Bath",
    size: "220 sq.ft",
    amenities: ["WiFi", "Food Available", "Metro Nearby", "Housekeeping", "RO Water"],
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=85",
    images: [{ url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=85", public_id: "seed_p002_1" }],
    description: "Affordable and hygienic PG accommodation with home-cooked meals option and 24/7 security. Just 3 minutes from Andheri East railway & metro hub.",
    availability: "available",
    featured: true
  },
  {
    id: "P003",
    brokerId: "B002",
    brokerName: "Sunita Patil",
    brokerPhone: "+91 98334 56789",
    brokerEmail: "sunita.broker@gharbazaar.com",
    agencyName: "Metro Stays & Housing",
    title: "Premium Studio Apartment with Balcony",
    location: "Borivali West, Mumbai",
    area: "borivali",
    type: "studio",
    price: 16000,
    deposit: 32000,
    badge: "Luxury",
    rating: 4.9,
    beds: "1 Bed",
    bath: "Private Bath",
    size: "320 sq.ft",
    amenities: ["Balcony", "Lift", "Parking", "AC", "Modular Kitchen"],
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1000&q=85",
    images: [{ url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1000&q=85", public_id: "seed_p003_1" }],
    description: "Modern self-contained studio apartment with private balcony, reserved two-wheeler parking and high-speed elevator in prime Borivali West.",
    availability: "available",
    featured: true
  },
  {
    id: "P004",
    brokerId: "B002",
    brokerName: "Sunita Patil",
    brokerPhone: "+91 98334 56789",
    brokerEmail: "sunita.broker@gharbazaar.com",
    agencyName: "Metro Stays & Housing",
    title: "Cozy PG for Working Professionals",
    location: "Goregaon East, Mumbai",
    area: "goregaon",
    type: "pg",
    price: 8500,
    deposit: 12000,
    badge: "Value",
    rating: 4.6,
    beds: "2 Beds",
    bath: "Shared Bath",
    size: "210 sq.ft",
    amenities: ["WiFi", "Food", "Power Backup", "Security", "Washing Machine"],
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1000&q=85",
    images: [{ url: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1000&q=85", public_id: "seed_p004_1" }],
    description: "Practical and pocket-friendly PG accommodation with everyday housekeeping, fast Wi-Fi and close proximity to NESCO IT Park.",
    availability: "available",
    featured: false
  },
  {
    id: "P005",
    brokerId: "B003",
    brokerName: "Vikram Mehta",
    brokerPhone: "+91 98192 34567",
    brokerEmail: "vikram.broker@gharbazaar.com",
    agencyName: "Urban Nest Properties",
    title: "Modern Private Room Near Metro",
    location: "Kandivali West, Mumbai",
    area: "kandivali",
    type: "private",
    price: 11000,
    deposit: 20000,
    badge: "Verified",
    rating: 4.7,
    beds: "1 Bed",
    bath: "Private Bath",
    size: "190 sq.ft",
    amenities: ["WiFi", "Metro Nearby", "Wardrobe", "Fan", "Gated Security"],
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=82",
    images: [{ url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=82", public_id: "seed_p005_1" }],
    description: "Immaculately maintained private room inside a secure gated complex. Offers dedicated wardrobe, modern bath fittings, and serene environment.",
    availability: "available",
    featured: false
  },
  {
    id: "P006",
    brokerId: "B003",
    brokerName: "Vikram Mehta",
    brokerPhone: "+91 98192 34567",
    brokerEmail: "vikram.broker@gharbazaar.com",
    agencyName: "Urban Nest Properties",
    title: "Executive Studio with City View",
    location: "Thane West, Mumbai",
    area: "thane",
    type: "studio",
    price: 19500,
    deposit: 40000,
    badge: "Premium",
    rating: 4.8,
    beds: "1 Bed",
    bath: "Private Bath",
    size: "380 sq.ft",
    amenities: ["Balcony", "AC", "Lift", "Parking", "Gym Access"],
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1000&q=85",
    images: [{ url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1000&q=85", public_id: "seed_p006_1" }],
    description: "Spacious executive studio apartment overlooking scenic greenery in Thane West. Fully air-conditioned with modern modular setup.",
    availability: "available",
    featured: true
  },
  {
    id: "P007",
    brokerId: "B001",
    brokerName: "Rajesh Sharma",
    brokerPhone: "+91 98201 12345",
    brokerEmail: "rajesh.broker@gharbazaar.com",
    agencyName: "Apex Realty Mumbai",
    title: "Student-Friendly PG Near NMIMS & Mithibai",
    location: "Vile Parle East, Mumbai",
    area: "vileparle",
    type: "pg",
    price: 9000,
    deposit: 15000,
    badge: "Student Pick",
    rating: 4.7,
    beds: "2 Beds",
    bath: "Shared Bath",
    size: "230 sq.ft",
    amenities: ["WiFi", "Food", "Study Desk", "Security", "CCTV"],
    image: "https://images.unsplash.com/photo-1529408632839-a54952c491e5?auto=format&fit=crop&w=1000&q=85",
    images: [{ url: "https://images.unsplash.com/photo-1529408632839-a54952c491e5?auto=format&fit=crop&w=1000&q=85", public_id: "seed_p007_1" }],
    description: "Comfortable and safe student PG with quiet study desk, daily nutritious breakfast and dinner, and walking distance to top colleges.",
    availability: "available",
    featured: false
  },
  {
    id: "P008",
    brokerId: "B002",
    brokerName: "Sunita Patil",
    brokerPhone: "+91 98334 56789",
    brokerEmail: "sunita.broker@gharbazaar.com",
    agencyName: "Metro Stays & Housing",
    title: "Fully Furnished 1BHK Apartment",
    location: "Jogeshwari West, Mumbai",
    area: "jogeshwari",
    type: "apartment",
    price: 24000,
    deposit: 50000,
    badge: "New",
    rating: 4.8,
    beds: "1 Bed",
    bath: "Private Bath",
    size: "450 sq.ft",
    amenities: ["WiFi", "AC", "TV", "Housekeeping", "Gas Pipeline", "Lift"],
    image: "https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=1000&q=85",
    images: [{ url: "https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=1000&q=85", public_id: "seed_p008_1" }],
    description: "Move-in ready complete 1BHK apartment with Smart TV, sofa set, gas pipeline, and dedicated washing machine. Close to SV Road.",
    availability: "available",
    featured: true
  },
  {
    id: "P009",
    brokerId: "B003",
    brokerName: "Vikram Mehta",
    brokerPhone: "+91 98192 34567",
    brokerEmail: "vikram.broker@gharbazaar.com",
    agencyName: "Urban Nest Properties",
    title: "Budget PG Near Local Train Station",
    location: "Dahisar East, Mumbai",
    area: "dahisar",
    type: "pg",
    price: 7800,
    deposit: 10000,
    badge: "Budget",
    rating: 4.5,
    beds: "3 Beds",
    bath: "Shared Bath",
    size: "250 sq.ft",
    amenities: ["WiFi", "Train Nearby", "Food", "Security"],
    image: "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=1000&q=85",
    images: [{ url: "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=1000&q=85", public_id: "seed_p009_1" }],
    description: "One of the best value-for-money rental accommodations for daily commuters. Easy 2-minute walking distance to Dahisar railway station.",
    availability: "available",
    featured: false
  },
  {
    id: "P010",
    brokerId: "B001",
    brokerName: "Rajesh Sharma",
    brokerPhone: "+91 98201 12345",
    brokerEmail: "rajesh.broker@gharbazaar.com",
    agencyName: "Apex Realty Mumbai",
    title: "Luxury 2BHK Lakeview Apartment",
    location: "Powai, Mumbai",
    area: "powai",
    type: "apartment",
    price: 36000,
    deposit: 80000,
    badge: "Luxury",
    rating: 5.0,
    beds: "2 Beds",
    bath: "2 Baths",
    size: "720 sq.ft",
    amenities: ["AC", "WiFi", "Gym", "Parking", "Swimming Pool", "Clubhouse"],
    image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1000&q=85",
    images: [{ url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1000&q=85", public_id: "seed_p010_1" }],
    description: "High-floor luxury residence in Powai offering panoramic lake views, world-class clubhouse amenities, covered parking, and 24/7 security concierge.",
    availability: "available",
    featured: true
  },
  {
    id: "P011",
    brokerId: "B002",
    brokerName: "Sunita Patil",
    brokerPhone: "+91 98334 56789",
    brokerEmail: "sunita.broker@gharbazaar.com",
    agencyName: "Metro Stays & Housing",
    title: "Compact Studio for Professionals",
    location: "Mulund West, Mumbai",
    area: "mulund",
    type: "studio",
    price: 17500,
    deposit: 35000,
    badge: "Verified",
    rating: 4.7,
    beds: "1 Bed",
    bath: "Private Bath",
    size: "300 sq.ft",
    amenities: ["Lift", "AC", "Kitchenette", "Security", "Intercom"],
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=85",
    images: [{ url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1000&q=85", public_id: "seed_p011_1" }],
    description: "Compact independent studio with fully functional kitchenette, energy-efficient inverter AC, modern elevator and security in Mulund West.",
    availability: "available",
    featured: false
  },
  {
    id: "P012",
    brokerId: "B003",
    brokerName: "Vikram Mehta",
    brokerPhone: "+91 98192 34567",
    brokerEmail: "vikram.broker@gharbazaar.com",
    agencyName: "Urban Nest Properties",
    title: "Affordable Furnished Room",
    location: "Mira Road, Mumbai",
    area: "miraroad",
    type: "private",
    price: 9500,
    deposit: 15000,
    badge: "Value",
    rating: 4.6,
    beds: "1 Bed",
    bath: "Shared Bath",
    size: "200 sq.ft",
    amenities: ["WiFi", "Wardrobe", "Parking", "Fan", "Water Filter"],
    image: "https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=1000&q=85",
    images: [{ url: "https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=1000&q=85", public_id: "seed_p012_1" }],
    description: "Well-ventilated private room in a friendly neighbourhood with parking, round-the-clock water supply and essential furnishings.",
    availability: "available",
    featured: false
  }
];

module.exports = {
  demoBrokers,
  demoUsers,
  demoProperties
};
